name: Build nginx images and push to Docker Hub

on:
  schedule:
    - cron: '13 0 * * 0'

  push:
    paths:
      - 'nginx/**'
      - '.github/workflows/build-nginx-images.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
    strategy:
      fail-fast: false
      matrix:
        nginx_version: ["1.24"]
    steps:
      - name: build and push docker images
        uses: 'OXID-eSales/github-actions/build_docker@v0'
        with:
          dockerhub_username: ${{ secrets.DOCKER_HUB_USER }}
          dockerhub_password: ${{ secrets.DOCKER_HUB_TOKEN }}
          image_name: nginx
          tags: |
            oxidesales/oxideshop-docker-nginx:${{ matrix.nginx_version }}
          build-args:  |
            NGINX_VERSION=${{ matrix.nginx_version }}
  finish:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK_URL }}"
    steps:
      - name: Send custom JSON data to Slack workflow
        if: ${{ always() && env.SLACK_WEBHOOK != '' }}
        uses: 'OXID-eSales/github-actions/slack_status@v1'
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          title: '${{ github.workflow }} on ${{ github.repository }} by ${{ github.actor }}'
          summary_list: |
            Repository%${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          job_list: |
            build%${{ needs.build.result }}
