name: Build sphinx image and push to Docker Hub

on:
  schedule:
    - cron: '* * */7 * *'
  push:
    paths:
      - 'sphinx/**'
      - '.github/workflows/build-sphinx-image.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: sphinx
          file: sphinx/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            oxidesales/oxideshop-docker-sphinx:latest