name: Build codeception image and push to Docker Hub

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - master
    paths:
      - 'codeception/**'
      - '.github/workflows/build-codeception-image.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
    steps:
      - name: build docker images
        uses: 'OXID-eSales/github-actions/build_docker@v4'
        with:
          dockerhub_username: ${{ secrets.DOCKER_HUB_USER }}
          dockerhub_password: ${{ secrets.DOCKER_HUB_TOKEN }}
          image_name: codeception
          platforms: linux/amd64,linux/arm64
          tags: |
            oxidesales/oxideshop-docker-codeception:latest
          build-args: ''

  finish:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: "${{ secrets.SLACK_DEVOPS_WEBHOOK_URL }}"
    steps:
      - name: Send custom JSON data to Slack workflow
        if: ${{ always() && env.SLACK_WEBHOOK != '' }}
        uses: 'OXID-eSales/github-actions/slack_status@v4'
        with:
          slack_webhook: ${{ secrets.SLACK_DEVOPS_WEBHOOK_URL }}
          title: '${{ github.workflow }} on ${{ github.repository }} by ${{ github.actor }}'
          summary_list: |
            Repository%${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          install_list: |
            build%${{ needs.build.result }}
