name: Build nginx images and push to Docker Hub

on:
  schedule:
    - cron: '13 0 * * 0'

  push:
    paths:
      - 'nginx/**'
      - '.github/workflows/build-nginx-images.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nginx_version: ["1.24"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: nginx
          file: nginx/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            NGINX_VERSION=${{ matrix.nginx_version }}
          tags: |
            oxidesales/oxideshop-docker-nginx:${{ matrix.nginx_version }}
