name: Build selenium images and push to Docker Hub

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - 'selenium/**'
      - '.github/workflows/build-selenium-images.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
    strategy:
      fail-fast: false
      matrix:
        selenium:
          - S3FF69
          - S3FF77
          - S3FF94
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into Docker Hub
        if: ${{github.event_name != 'pull_request' && env.docker_hub_user != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: selenium/${{ matrix.selenium }}
          file: selenium/${{ matrix.selenium }}/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' && env.docker_hub_user != '' }}
          tags: |
            oxidesales/oxideshop-docker-selenium:${{ matrix.selenium }}