name: Build selenium images and push to Docker Hub

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - 'selenium/**'
      - '.github/workflows/build-selenium-images.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
    strategy:
      fail-fast: false
      matrix:
        selenium:
          - S3FF69
          - S3FF77
          - S3FF94
    steps:
      - name: build and push docker images
        uses: 'OXID-eSales/github-actions/build_docker@v0'
        with:
          dockerhub_username: ${{ secrets.DOCKER_HUB_USER }}
          dockerhub_password: ${{ secrets.DOCKER_HUB_TOKEN }}
          image_name: selenium/${{ matrix.selenium }}
          tags: |
            oxidesales/oxideshop-docker-selenium:${{ matrix.selenium }}
          build-args: ''
  finish:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK_URL }}"
    steps:
      - name: Send custom JSON data to Slack workflow
        if: ${{ always() && env.SLACK_WEBHOOK != '' }}
        uses: 'OXID-eSales/github-actions/slack_status@v1'
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          title: '${{ github.workflow }} on ${{ github.repository }} by ${{ github.actor }}'
          summary_list: |
            Repository%${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          job_list: |
            build%${{ needs.build.result }}
